DROP SEQUENCE MC_SEQ;
DROP TABLE CLAIM cascade constraints;
DROP TABLE LOSS_INFO_TYPE;
DROP TABLE VEHICLE_INFO;

CREATE TABLE CLAIM (
	ID NUMBER(22, 0) NOT NULL,
	CLAIM_NUMBER VARCHAR2(50) NOT NULL,
	CLAIMANT_FIRST_NAME VARCHAR2(64),
	CLAIMANT_LAST_NAME VARCHAR2(64),
	STATUS_CODE VARCHAR(6),
	LOSS_DATE TIMESTAMP,
	ASSIGNED_ADJUSTERID NUMBER(22, 0),
	PRIMARY KEY(ID)
);

CREATE TABLE LOSS_INFO_TYPE (
	CLAIM_ID NUMBER(22, 0) NOT NULL,
	CAUSE_OF_LOSS_CODE VARCHAR2(25),
	REPORTED_DATE TIMESTAMP,
	LOSS_DESCRIPTION VARCHAR2(4000),
	PRIMARY KEY(CLAIM_ID)
);
ALTER TABLE LOSS_INFO_TYPE
ADD ( CONSTRAINT LIT_FK
FOREIGN KEY(CLAIM_ID)
REFERENCES CLAIM(ID) );

CREATE TABLE VEHICLE_INFO (
	CLAIM_ID NUMBER(22, 0) NOT NULL,
	MODEL_YEAR NUMBER(4, 0),
	MAKE_DESCRIPTION VARCHAR2(200),
	MODEL_DESCRIPTION VARCHAR2(200),
	ENGINE_DESCRIPTION VARCHAR2(200),
	EXTERIOR_COLOR VARCHAR2(50),
	VIN VARCHAR2(100),
	LIC_PLATE VARCHAR2(50),
	LIC_PLATE_STATE VARCHAR2(20),
	LIC_PLATE_EXPIRATION DATE,
	DAMAGE_DESCRIPTION VARCHAR2(4000),
	MILEAGE NUMBER(10, 0),
	PRIMARY KEY(CLAIM_ID)
);
ALTER TABLE VEHICLE_INFO
ADD ( CONSTRAINT VI_FK
FOREIGN KEY(CLAIM_ID)
REFERENCES CLAIM(ID) );

CREATE SEQUENCE  "MC_SEQ"  MINVALUE 100 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 100 CACHE 20 NOORDER  NOCYCLE ;


